/*
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * API version: 4.30.43656
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LoginData struct {
	ProductName    string `json:"productName,omitempty"`
	Version        string `json:"version,omitempty"`
	EsiaLoginPage  string `json:"esiaLoginPage,omitempty"`
	CacheVer       string `json:"cacheVer,omitempty"`
	SchoolLogin    bool   `json:"schoolLogin,omitempty"`
	EmLogin        bool   `json:"emLogin,omitempty"`
	WindowsAuth    bool   `json:"windowsAuth,omitempty"`
	EnableSms      bool   `json:"enableSms,omitempty"`
	EsiaMainAuth   bool   `json:"esiaMainAuth,omitempty"`
	EsiaButton     bool   `json:"esiaButton,omitempty"`
	SignatureLogin bool   `json:"signatureLogin,omitempty"`
}
