/*
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * API version: 4.30.43656
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PrepareEmLoginForm struct {
	Countries []PrepareEmLoginFormCountries `json:"countries,omitempty"`
	States    []PrepareEmLoginFormCountries `json:"states,omitempty"`
	Hlevels   []PrepareEmLoginFormCountries `json:"hlevels,omitempty"`
	Ems       []PrepareEmLoginFormCountries `json:"ems,omitempty"`
	EmCid     int32                         `json:"em_cid,omitempty"`
	EmSid     int32                         `json:"em_sid,omitempty"`
	Hlevel    int32                         `json:"hlevel,omitempty"`
	EmId      int32                         `json:"emId,omitempty"`
}
