/*
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * API version: 4.30.43656
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Mark struct {
	AssignmentId int32 `json:"assignmentId,omitempty"`
	StudentId    int32 `json:"studentId,omitempty"`
	Mark         int32 `json:"mark,omitempty"`
	DutyMark     bool  `json:"dutyMark,omitempty"`
}
