/*
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiaryWeekDays struct {
	Date    string        `json:"date,omitempty"`
	Lessons []DiaryLesson `json:"lessons,omitempty"`
}
