FROM golang:1.19-alpine as builder

COPY ./ /go/src/github.com/kmlebedev/netcitybot/
WORKDIR /go/src/github.com/kmlebedev/netcitybot

RUN CGO_ENABLED=0 GOOS=linux go install

FROM alpine AS final

USER nobody
COPY --from=builder /go/bin/netcitybot /usr/bin/

ENTRYPOINT ["/usr/bin/netcitybot"]
