name: "docker: build release container"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-default-release-container:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.5.0
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            kmlebedev/netcitybot
          tags: |
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=netcitybot
            org.opencontainers.image.description=NetCityBot is a API client and telegram bot for "Network City. Education" written in Golang
            org.opencontainers.image.vendor=Konstantin Lebedev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ./docker/Dockerfile.local_go_build
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
